name: Atmos infrastructure CD

on:
#  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  atmos-infrastructure-cd:
    name: Atmos infrastructure CD
    runs-on: ubuntu-latest
    container:
      image: mtweeman/hajle-silesia_provisioning-toolbox:0.8.8

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Atmos version
        run: |
          atmos version
          pwd
          whoami
      - name: Atmos affected
        uses: cloudposse/github-action-atmos-affected-stacks@v5
        with:
          atmos-config-path: rootfs/usr/local/etc/atmos
          install-atmos: false
        outputs:
          matrix: ${{ steps.affected.outputs.matrix }}
          has-affected-stacks: ${{ steps.affected.outputs.has-affected-stacks }}
